- id: '1540780737178'
  alias: Front Lights @ Sunset
  initial_state: true
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.front_lights
    service: light.turn_on
- id: '1540781674303'
  alias: Front Lawn Light @ Sunrise
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.front_lawn
    service: light.turn_off
  initial_state: true
- id: '1547425470922'
  alias: Porch Lights Off @ Night
  trigger:
  - at: 00:00:30
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.porch_lights
    service: light.turn_off
  initial_state: true
- id: alarm_armed_away
  alias: '[Alarm] Away Mode Armed'
  trigger:
  - entity_id: alarm_control_panel.house
    platform: state
    to: armed_away
  action:
  - data:
      message: Alarm Away Mode Armed
      target:
      - email/redacted
    service: notify.pushbullet
  - data:
      data:
        type: tts
      message: Home Alarm is activated in Away Mode.
      target:
      - Living Room Echo
    service: notify.alexa_media
  - data:
      message: Home Alarm is activated in Away Mode.
    service: notify.redacted
  - entity_id: lock.lock_front_door_lock
    service: lock.lock
  initial_state: true
- id: alarm_armed_home
  alias: '[Alarm] Home Mode Armed'
  trigger:
  - entity_id: alarm_control_panel.house
    platform: state
    to: armed_home
  action:
  - data:
      message: Alarm Home Mode Armed
      target:
      - email/redacted
    service: notify.pushbullet
  - data:
      data:
        type: tts
      message: The house alarm has been armed in home mode.
      target:
      - Echo office
      - Living Room Echo
    service: notify.alexa_media
  - data:
      entity_id: lock.lock_front_door_lock
    service: lock.lock
  - data:
      message: Home Alarm is armed in Home mode.
    service: notify.mobile_app_matt_phone
  initial_state: true
- id: alarm_arming_away
  alias: '[Alarm] Away Mode Arming'
  trigger:
  - entity_id: alarm_control_panel.house
    platform: state
    to: pending
  action:
  - data:
      data:
        type: tts
      message: Home alarm is activating in Away Mode. Ensure all doors and windows
        are shut. Goodbye.
      target:
      - Living Room Echo
    service: notify.alexa_media
  initial_state: true
- id: alarm_disarmed
  alias: '[Alarm] Disarmed'
  trigger:
  - entity_id: alarm_control_panel.house
    platform: state
    to: disarmed
  action:
  - data:
      message: Alarm Disabled
      target:
      - email/redacted
    service: notify.pushbullet
  - data:
      data:
        type: tts
      message: The house alarm has been Deactivated
      target:
      - Living Room Echo
    service: notify.alexa_media
  - alias: ''
    data:
      entity_id: switch.arduino_gw_0_52
    service: switch.turn_off
  - data:
      message: Home Alarm has been deactivated.
    service: notify.redacted
  initial_state: true
- id: alarm_triggered
  alias: '[Alarm] Triggered'
  trigger:
  - entity_id: alarm_control_panel.house
    platform: state
    to: triggered
  action:
  - data:
      data:
        method: all
        type: all
      message: Warning! The home alarm has been triggered by {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name}}.
        The authorities have been notified. Leave immediately!
      target:
      - Echo office
      - Living Room Echo
      title: Home Alarm TRIGGERED by {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name}}.
    service: notify.alexa_media
  - data:
      message: ALARM TRIGGERED!!! {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name
        }} has been tripped.
      target:
      - email/redacted
    service: notify.pushbullet
  - data:
      entity_id: switch.arduino_gw_0_52
    service: switch.turn_on
  - data:
      message: Home Alarm TRIGGERED by {{states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name}}.
      title: Alarm triggered!
    service: notify.redacted
  - entity_id: switch.backyard_state
    service: switch.turn_on
  - entity_id: switch.backyard2_state
    service: switch.turn_on
  - entity_id: switch.front_porch_state
    service: switch.turn_on
  - entity_id: switch.driveway_state
    service: switch.turn_on
  initial_state: true
- id: alarm_warning
  alias: '[Alarm] Warning'
  trigger:
  - entity_id: alarm_control_panel.house
    platform: state
    to: warning
  action:
  - data:
      message: ALARM Warning {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name
        }} has been tripped.
      target:
      - email/redacted
    service: notify.pushbullet
  - data:
      data:
        method: all
        type: tts
      message: The house alarm has been activated. {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name
        }} has been tripped. Please deactivate immediately.
      target:
      - Living Room Echo
      title: Home Alarm WARNING
    service: notify.alexa_media
  - data:
      message: Alarm warning! {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][
        states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name
        }} has been tripped.
      title: Warning!
    service: notify.redacted
  initial_state: true
- id: '1556842770224'
  alias: Front Door Unlock Upon Arriving Home
  trigger:
  - entity_id: binary_sensor.ring_front_door_motion
    platform: state
    to: 'on'
  condition:
  - condition: zone
    entity_id: person.matt
    zone: zone.home
  action:
  - data:
      armed_state: disarmed
    service: alarm_control_panel.alarm_disarm
  - entity_id: lock.schlage_allegion_be469_touchscreen_deadbolt_locked_frontdoor
    service: lock.unlock
- id: '1557103120900'
  alias: Den Light On on Motion
  trigger:
  - entity_id: binary_sensor.arduino_gw_0_34
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.den_light
    service: switch.turn_on
- id: '1557103744211'
  alias: Den Light Off After No Motion at Night
  trigger:
  - entity_id: binary_sensor.arduino_gw_0_34
    for: 00:05:00
    platform: state
    to: 'off'
  condition:
  - after: '23:00'
    condition: time
  action:
  - data:
      entity_id: switch.den_light
    service: switch.turn_off
- id: '1562248478361'
  alias: HA Update Available
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.version_available'') > states(''sensor.current_version'')
      }}'
  condition: []
  action:
  - data:
      message: HA Version {{ states('sensor.version_available') }} Available!
      title: HASS
    service: persistent_notification.create
- id: '1571615535154'
  alias: Halloween - Front Porch Lights
  description: ''
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  condition: []
  action:
  - data:
      brightness: 175
      color_name: orange
      entity_id: light.front_porch_1
    service: light.turn_on
  - data:
      brightness: 175
      color_name: black
      entity_id: light.front_porch_2
    service: light.turn_on
- id: '1571874372030'
  alias: Living Room Roku SS
  description: ''
  trigger:
  - entity_id: input_select.roku_source
    platform: state
  condition:
    condition: state
    entity_id: sensor.harmony_hub
    state: Living Room Watch Roku
  action:
  - service: media_player.select_source
    data_template:
      entity_id: media_player.living_room_roku_2
      source: "{% if is_state(\"input_select.roku_source\", \"Netflix\") %}\n  12\n\
        {%-elif is_state(\"input_select.roku_source\", \"Hulu\") %}\n  2285\n{%-elif\
        \ is_state(\"input_select.roku_source\", \"Plex\") %}\n  13535\n{%-elif is_state(\"\
        input_select.roku_source\", \"Pluto TV\") %}\n  74519\n{%-elif is_state(\"\
        input_select.roku_source\", \"YouTube\") %}\n  837\n{%-elif is_state(\"input_select.roku_source\"\
        , \"Prime Video\") %}\n  13\n{%-elif is_state(\"input_select.roku_source\"\
        , \"History\") %}\n  35059\n{%-elif is_state(\"input_select.roku_source\"\
        , \"ESPN\") %}\n  34376\n{%-elif is_state(\"input_select.roku_source\", \"\
        Fox Sports\") %}\n  95307\n{%-elif is_state(\"input_select.roku_source\",\
        \ \"HGTV Go\") %}\n  75619\n{%-elif is_state(\"input_select.roku_source\"\
        , \"Discovery Go\") %}\n  96041\n{%-elif is_state(\"input_select.roku_source\"\
        , \"Food Network\") %}\n  75617\n{%-elif is_state(\"input_select.roku_source\"\
        , \"NBC\") %}\n  68669\n{%-elif is_state(\"input_select.roku_source\", \"\
        The Roku Channel\") %}\n  151908\n{%-elif is_state(\"input_select.roku_source\"\
        , \"Pandora\") %}\n  28\n{%-elif is_state(\"input_select.roku_source\", \"\
        iHeart Radio\") %}\n  20197\n{%-elif is_state(\"input_select.roku_source\"\
        , \"Weather Channel\") %}\n  273862\n{%-elif is_state(\"input_select.roku_source\"\
        , \"Weather Nation\") %}\n  30547\n{%-elif is_state(\"input_select.roku_source\"\
        , \"Weather Network\") %}\n  84056\n{% else %}\n  none\n{% endif %}\n"
- id: '1572034382208'
  alias: Sleep Timer
  description: ''
  trigger:
  - entity_id: input_select.sleep_timer
    platform: state
  condition: []
  action:
  - delay:
      minutes: '{{ states(''input_select.sleep_timer'') }}'
  - data:
      activity: PowerOff
      entity_id: remote.living_room
    service: remote.turn_on
- id: hacs_new_repo
  alias: HACS new repo notification
  trigger:
    platform: event
    event_type: hacs/repository
    event_data:
      action: registration
  condition:
    condition: template
    value_template: '{{ trigger.event.data.repository is defined }}'
  action:
    service: persistent_notification.create
    data_template:
      title: New repository added in HACS
      message: '{% set repo = trigger.event.data.repository %} {% set id = trigger.event.data.repository_id
        %} [{{ repo }}](/hacs/repository/{{ id}}) was just added to HACS.'
- id: hacs_updates
  alias: HACS updates pending
  trigger:
    platform: state
    entity_id: sensor.hacs
  condition:
  - condition: template
    value_template: '{{ states(trigger.entity_id) != ''unknown''}}'
  - condition: template
    value_template: '{{ (states(trigger.entity_id) | float) != 0}}'
  action:
    service: persistent_notification.create
    data_template:
      title: Updates pending in HACS
      message: "{% for repo in state_attr(trigger.entity_id, 'repositories') %}\n\
        \  **{{ repo.display_name }}** _{{ repo[\"installed version\"] }}_ -> _{{\
        \ repo[\"available version\"]}}_\n{% endfor %}"
- id: rpi_power
  alias: Power Supply Problem Notification
  trigger:
  - platform: numeric_state
    entity_id: sensor.rpi_power_status
    value_template: '{{ state.attributes.value }}'
    above: 0
    for:
      minutes: 5
  condition:
  action:
  - service: persistent_notification.create
    data_template:
      message: 'HASS Power reported {{ states.sensor.rpi_power_status.state }}. The
        state had changed from {{ trigger.from_state.state }} '
      title: HASS Power Supply Issue
  - service: notify.mobile_app_matt_phone
    data_template:
      message: HASS Power reported {{ states.sensor.rpi_power_status.state }}. The
        state had changed from {{ trigger.from_state.state }}
      title: HASS Power Supply Issue
- id: '1577103385700'
  alias: '[Alarm] Night Mode Armed'
  description: ''
  trigger:
  - entity_id: alarm_control_panel.house
    platform: state
    to: armed_night
  condition: []
  action:
  - data:
      data:
        type: tts
      message: Home Alarm is activated in Away Mode.
      target:
      - Living Room Echo
    service: notify.alexa_media
  - data:
      Message: Home Alarm has been armed in night mode. Goodnight.
      title: Night Mode Armed
    service: notify.redacted
- id: '1577104366007'
  alias: Vacation Mode
  description: ''
  trigger:
  - event: sunset
    offset: -03:00:00
    platform: sun
  condition:
  - condition: state
    entity_id: device_tracker.oneplus_a6013_2
    state: not_home
  - condition: state
    entity_id: alarm_control_panel.house
    state: armed_away
  action:
  - alias: ''
    data: {}
    entity_id: switch.den_light
    service: switch.turn_on
- id: '1578883413012'
  alias: Speedtest update
  description: ''
  trigger:
  - entity_id: sensor.speedtest_upload
    platform: state
  condition: []
  action:
  - data:
      message: The current download speed for HASS is {{ states('sensor.speedtest_download')
        }}, while the current upload speed is {{ states('sensor.speedtest_upload')
        }}.
      target: '666061409053966344'
    service: notify.discord
- id: '1586561275990'
  alias: Home Assistant start-up
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data: {}
    service: script.1586561224524
- id: '1586561475101'
  alias: Home Assistant start-up
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data: {}
    service: script.1586561224524
- id: '1586561569170'
  alias: zwave loaded start system
  description: ''
  trigger:
  - event_data: {}
    event_type: zwave.network_ready
    platform: event
  - event_data: {}
    event_type: zwave.network_complete
    platform: event
  - event_data: {}
    event_type: zwave.network_complete_some_dead
    platform: event
  condition: []
  action:
  - data: {}
    service: script.1586561168701
