homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

alexa_media:
  accounts:
    - email: !secret amazon-user
      password: !secret amazon-pass
      url: amazon.com
      include_devices:
        - "Echo office"
        - "Echo Show"
        - "Living Room Echo"

apcupsd:
  host: 127.0.0.1
  port: 3551

breaking_changes:

#custom_updater:
#  card_urls:
#    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json
#  component_urls:
#    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json

camera:
  - platform: ffmpeg
    input: 192.168.2.41
  - platform: ffmpeg
    input: 192.168.2.42
  - platform: ffmpeg
    input: 192.168.2.43

default_config:

device_tracker:

frontend:
  themes: !include themes/slate.yaml

hacs:
  token: af4bb5c6c285d66a245092594a25b25f3a99ef06
  sidepanel_title: HACS
  python_script: true
  theme: true
  options:
    experimental: true

#http:
#  base_url: http://hass.colemanonline.net:8123
#  use_x_forwarded_for: true
#  trusted_proxies:
#    - 192.168.2.100

hue:
  bridges:
    - host: 192.168.2.204

influxdb:

input_select:
  destination:
    name: destination
    options:
      - Home
      - Work
      - Nicholas
      - Johnathon
  roku_source:
    name: roku_source
    options:
      - Netflix
      - Hulu
      - Plex
      - YouTube
      - Fox Sports
      - Pluto TV
      - The Roku Channel
      - Tubi
  sleep_timer:
    name: Sleep Timer
    options:
      - 0
      - 30
      - 60
      - 90
      - 120

logger:
  default: info
  logs:
    hacs: debug

lovelace:
  mode: yaml

mobile_app:

# MQTT
mqtt:
  broker: 127.0.0.1
  port: 1888

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

notify:
  # Pushbullet notifications
  - name: pushbullet
    platform: pushbullet
    api_key: o.HyKdUqIgnaoC598rkdLWji73ee25DDUL

pi_hole:
  host: '192.168.2.254'

plex:
  token: LWzyHYspyX9Z8E71s9es

recorder:
  purge_keep_days: 14

remote:
  - platform: harmony
    name: Living Room
    host: 192.168.2.45

ring:
  username: !secret ring_client_id
  password: !secret ring_client_password

roku:
  - host: 192.168.2.8
  - host: 192.168.2.10
  - host: 192.168.2.11

switch: !include switch.yaml

# Text to speech
#tts:
#  - platform: google

weather:
  platform: openweathermap
  api_key: !secret openweathermap-api_key

wemo:
  discovery: true

zwave:
  usb_path: /dev/ttyACM0
  network_key: "0x48, 0xE7, 0x5A, 0x4F, 0x14, 0x30, 0x60, 0x0D, 0x08, 0x07, 0x53, 0xAD, 0xF1, 0xFF, 0x01, 0xFF"
  autoheal: true

alarm_control_panel: !include resources/bwalarm/bwalarm.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
group: !include groups.yaml
mysensors: !include mysensors_config.yaml
#panel_custom: !include panel_custom.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
