homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  # Allow local network access with no login
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.2.0/24
    - type: homeassistant

alexa_media:
  accounts:
    - email: !secret amazon-user
      password: !secret amazon-pass
      url: amazon.com
      include_devices:
        - "Echo office"
        - "Echo Show"
        - "Living Room Echo"

apcupsd:
  host: 127.0.0.1
  port: 3551

breaking_changes:

camera:
  - platform: ffmpeg
    input: 192.168.2.41
  - platform: ffmpeg
    input: 192.168.2.42
  - platform: ffmpeg
    input: 192.168.2.43

cloud:

config:

device_tracker:
  - platform: tile
    username: !secret tile_email_address
    password: !secret tile_password

frontend:
  themes: !include themes/slate.yaml

hacs:
  token: xxxxxxxx
  sidepanel_title: Community Store
  python_script: true
  theme: true
  options:
    experimental: true

history:
  exclude:
    domains:
      - automation
      - input_boolean
      - input_datetime
      - input_select
      - input_text
      - script

hue:
  bridges:
    - host: 192.168.2.204

influxdb:

input_select:
  destination:
    name: destination
    options:
      - Home
      - Work
      - Nicholas
      - Johnathon
  roku_source:
    name: roku_source
    options:
      - Netflix
      - Hulu
      - Plex
      - YouTube
      - History
      - Prime Video
      - ESPN
      - Fox Sports
      - Pluto TV
      - HGTV Go
      - Discovery Go
      - Food Network
      - NBC
      - The Roku Channel
      - Pandora
      - iHeart Radio
      - Weather Channel
      - Weather Nation
      - Weather Network

  sleep_timer:
    name: Sleep Timer
    options:
      - 0
      - 30
      - 60
      - 90
      - 120

input_text:
  roku_source:
    name: roku source

logbook:
  exclude:
    domains:
      - automation
      - input_boolean
      - input_datetime
      - input_select
      - input_text
      - script

logger:
  default: info
  logs:
    hacs: debug

lovelace:
  mode: yaml

map:

mobile_app:

# MQTT
mqtt:
  broker: 127.0.0.1
  port: 1888

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

notify:
  # Pushbullet notifications
  - name: pushbullet
    platform: pushbullet
    api_key: xxxxxxxx

person:

pi_hole:
  host: '192.168.2.254'

plex:
  token: xxxxxxxx

recorder:
  purge_keep_days: 7

remote:
  - platform: harmony
    name: Living Room
    host: 192.168.2.45

ring:
  username: !secret ring_client_id
  password: !secret ring_client_password

roku:
  - host: 192.168.2.8
  - host: 192.168.2.10
  - host: 192.168.2.11

ssdp:

sun:

system_health:

updater:
  reporting: false

weather:
  platform: openweathermap
  api_key: !secret openweathermap-api_key

wemo:
  discovery: true

zeroconf:

zwave:
  usb_path: /dev/ttyACM0
  network_key: xxxxxxxx
  autoheal: true

alarm_control_panel: !include resources/bwalarm/bwalarm.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
group: !include groups.yaml
mysensors: !include mysensors_config.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
