homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

alexa_media:
  accounts:
    - email: !secret amazon-user
      password: !secret amazon-pass
      url: amazon.com
      include_devices:
        - "Echo office"
        - "Echo Show"
        - "Living Room Echo"

apcupsd:
  host: 127.0.0.1
  port: 3551

# custom_updater:
#   component_urls:
#     - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

device_tracker:

http:
  base_url: http://xxxx
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.2.100

input_select:
  destination:
    name: destination
    options:
      - Home
      - Work
      - Nicholas
      - Johnathon

media_player:
  - platform: plex

# MQTT
mqtt:
  broker: 127.0.0.1
  port: 1888

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

notify:
  # Pushbullet notifications
  - name: pushbullet
    platform: pushbullet
    api_key: xxxxxx

  # HANotify (used for Ariela)
  - name: android
    platform: fcm-android

  - platform: alexa_media
    name: alexa_media

remote:
  - platform: harmony
    name: Living Room
    host: 192.168.2.5

ring:
  username: !secret ring_client_id
  password: !secret ring_client_password

switch:
  - platform: mqtt
    name: "Overhead Garage Door"
    state_topic: "/Garage/Ovhd_Garage_Status/Ovhd_Garage_Status"
    command_topic: "/Garage/gpio/12"
    payload_on: 1
    payload_off: 1

  - platform: mqtt
    name: "Arm Alarm Home"
    command_topic: "home/alarm/set"
    state_topic: "home/alarm"
    payload_on: "ARM_HOME"
    payload_off: "DISARM"
    state_on: "armed_home"
    state_off: "disarmed"

  - platform: mqtt
    name: "Arm Alarm Away"
    command_topic: "home/alarm/set"
    state_topic: "home/alarm"
    payload_on: "ARM_AWAY"
    payload_off: "DISARM"
    state_on: "armed_away"
    state_off: "disarmed"

  - platform: template
    switches:
      hulu:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Hulu') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Hulu'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'

      netflix:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Netflix') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Netflix'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'

      plex:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Plex') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Plex'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'

      music:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Music') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'Music'
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'

      hulu_den:
        value_template: "{{ is_state_attr('media_player.den_roku', 'source', 'Hulu') }}"
        turn_on:
          service: media_player.select_source
          data:
            entity_id: media_player.den_roku
            source: 'Hulu'
        turn_off:
          service: remote.send_command
          data:
            entity_id: remote.den_roku
            command: power

      netflix_den:
        value_template: "{{ is_state_attr('media_player.den_roku', 'source', 'Netflix') }}"
        turn_on:
          service: media_player.select_source
          data:
            entity_id: media_player.den_roku
            activity: 'Netflix'
        turn_off:
          service: remote.send_command
          data:
            entity_id: remote.den_roku
            command: power

      plex_den:
        value_template: "{{ is_state_attr('media_player.den_roku', 'source', 'Plex') }}"
        turn_on:
          service: media_player.select_source
          data:
            entity_id: media_player.den_roku
            activity: 'Plex'
        turn_off:
          service: remote.send_command
          data:
            entity_id: remote.den_roku
            command: power

# Text to speech
#tts:
#  - platform: google

weather:
  platform: openweathermap
  api_key: !secret openweathermap-api_key

wemo:
  discovery: true

alarm_control_panel: !include alarm.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
group: !include groups.yaml
mysensors: !include mysensors_config.yaml
panel_custom: !include panel_custom.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
