homeassistant:
  name: Home
  auth_providers:
    - type: homeassistant    
    - type: trusted_networks
      trusted_networks:
        - 192.168.2.0/24
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: !secret time_zone
  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /config

breaking_changes:

browser_mod:

camera:
  - platform: ffmpeg
    name: Front_Porch
    input: http://192.168.2.100:8081

  - platform: ffmpeg
    name: Driveway
    input: http://192.168.2.100:8082

cloud:

config:

device_tracker:
  - platform: google_maps
    username: !secret google_email

frontend:
  themes: !include_dir_merge_named themes

hacs:
  token: redacted
  sidepanel_title: Community Store
  options:
    experimental: true

history:
  exclude:
    domains:
      - automation
      - input_boolean
      - input_datetime
      - input_select
      - input_text
      - script

input_boolean:
  allow_automation_execution:
    name: 'Allow Automation'
    initial: on
  system_ready:
    name: 'System Ready'
    initial: off

input_number:
  fullykiosk_brightness_slider:
    name: Brightness
    icon: 'mdi:brightness-percent'
    initial: 20
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"

input_select:
  roku_source:
    name: Roku Source
    options:
      - Netflix
      - Hulu
      - Plex
      - YouTube
      - History
      - Prime Video
      - ESPN
      - Fox Sports
      - Pluto TV
      - HGTV Go
      - Discovery Go
      - Food Network
      - NBC
      - The Roku Channel
      - Pandora
      - iHeart Radio
      - Weather Channel
      - Weather Nation
      - Weather Network
    initial: Netflix

  sleep_timer:
    name: Sleep Timer
    initial: 0
    options:
      - 0
      - 30
      - 60
      - 90
      - 120
  
input_text:
  roku_source:
    name: roku source

logbook:

logger:
  default: info

lovelace:
  mode: yaml
  resources:
  - type: js
    url: /hacsfiles/bar-card/bar-card.js
  - type: module
    url: /hacsfiles/button-card/button-card.js
  - type: module
    url: /hacsfiles/button-entity-row/button-entity-row.js
  - type: module
    url: /hacsfiles/lovelace-card-mod/card-mod.js
  - type: module
    url: /hacsfiles/lovelace-card-tools/card-tools.js
  - type: module
    url: /hacsfiles/circle-sensor-card/circle-sensor-card.js
  - type: module
    url: /hacsfiles/custom-header/custom-header.js
  - type: module
    url: /hacsfiles/lovelace-gap-card/gap-card.js
  - type: module
    url: /hacsfiles/lovelace-layout-card/layout-card.js
  - type: js
    url: /hacsfiles/light-entity-card/light-entity-card.js
  - type: module 
    url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
  - type: module
    url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /hacsfiles/swipe-card/swipe-card.js
  - type: js
    url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
  - type: js
    url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
  - type: module
    url: /hacsfiles/roku-card/roku-card.js
  - type: css
    url: 'https://sf.abarba.me/font.css'
  - type: module
    url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js

map:

mobile_app:

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

notify:
  # Pushbullet notifications
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api

  # This home's own Discord server
  - name: discord
    platform: discord
    token: !secret discord_bot_token

person:

recorder:
  db_url: redacted
  purge_keep_days: 60
  exclude:
    domains:
      - input_datetime
      - input_select
      - input_text
      - script
      - zwave

remote:
  - platform: harmony
    name: Living Room
    host: 192.168.2.45

roku:
  - host: 192.168.2.12
  - host: 192.168.2.11
  - host: 192.168.2.13

ssdp:

stream:

sun:

system_health:

updater:
  reporting: false

weather: 
  - platform: openweathermap
    api_key: !secret weather_key
    mode: freedaily
    latitude: !secret latitude
    longitude: !secret longitude
    
zeroconf:

alarm_control_panel: !include resources/bwalarm/bwalarm.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
group: !include groups.yaml
mysensors: !include mysensors_config.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
