# UPS sensor
- platform: apcupsd
  resources:
    - bcharge
    - timeleft
    - linev
    - loadpct
    - nominv
    - nompower
    - numxfers
    - lastxfer
    - status
    - tonbatt
    - cumonbatt
    - battv
    - nombattv

- platform: template
  sensors:
  #Waze travel time
    dest_address:
      value_template: >-
        {%- if is_state("input_select.destination", "Home") -%}
          !secret home_address
        {%- elif is_state("input_select.destination", "Work") -%}
          !secret work_address
        {%- elif is_state("input_select.destination", "Nicholas") -%}
          !secret nick_address
        {%- elif is_state("input_select.destination", "Johnathon") -%}
          !secret john_address
        {%- else -%}
          Unknown
        {%- endif %}

    harmony_hub:
      value_template: '{{ states.remote.living_room.attributes.current_activity }}'
      friendly_name: Harmony

    den_media:
      value_template: '{{ states.media_player.den_roku.attributes.source }}'
      friendly_name: 'Den TV Source'

- platform: waze_travel_time
  name: "Me to destination"
  origin: device_tracker.matt_phone
  destination: sensor.dest_address
  region: 'US'

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: openweathermap
  api_key: !secret openweathermap-api_key
  monitored_conditions:
    - weather
  forecast: true
