- platform: deluge
  host: 192.168.2.190
  username: !secret deluge_user
  password: !secret deluge_pass
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'

- platform: fail2ban
  jails:
    - hass-iptables
    - nginx-badbots
    - nginx-botsearch
    - nginx-http-auth
    - ssh
  file_path: /fail2ban/fail2ban.log
  
- platform: mqtt
  name: "Washing Machine Power"
  state_topic: "tele/sonoff/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"

- platform: mqtt
  name: "Washing Machine Current"
  state_topic: "tele/sonoff/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Current"] }}'
  unit_of_measurement: "A"

- platform: mqtt
  name: 'Alarm Tablet Battery'
  state_topic: 'fully/deviceInfo/7ab54201-19afee03'
  json_attributes_topic: 'fully/deviceInfo/7ab54201-19afee03'
  value_template: '{{ value_json.batteryLevel }}'
  device_class: battery
  unit_of_measurement: '%'

- platform: mqtt
  name: 'Alarm Tablet Plugged In'
  state_topic: 'fully/deviceInfo/7ab54201-19afee03'
  json_attributes_topic: 'fully/deviceInfo/7ab54201-19afee03'
  value_template: '{{ value_json.isPlugged }}'

- platform: mqtt
  name: 'Remote Tablet Battery'
  state_topic: 'fully/deviceInfo/1d505ee2-8fa3d3c7'
  json_attributes_topic: 'fully/deviceInfo/1d505ee2-8fa3d3c7'
  value_template: '{{ value_json.batteryLevel }}'
  device_class: battery
  unit_of_measurement: '%'

- platform: mqtt
  name: 'Remote Tablet Plugged In'
  state_topic: 'fully/deviceInfo/1d505ee2-8fa3d3c7'
  json_attributes_topic: 'fully/deviceInfo/1d505ee2-8fa3d3c7'
  value_template: '{{ value_json.isPlugged }}'

- platform: mqtt
  name: 'Wall Tablet Battery'
  state_topic: 'fully/deviceInfo/b29c1227-f08da7ba'
  json_attributes_topic: 'fully/deviceInfo/b29c1227-f08da7ba'
  value_template: '{{ value_json.batteryLevel }}'
  device_class: battery
  unit_of_measurement: '%'

- platform: mqtt
  name: 'Wall Tablet Plugged In'
  state_topic: 'fully/deviceInfo/b29c1227-f08da7ba'
  json_attributes_topic: 'fully/deviceInfo/b29c1227-f08da7ba'
  value_template: '{{ value_json.isPlugged }}'

- platform: rpi_power
  text_state: true

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot    

- platform: template
  sensors:
    harmony_hub:
      value_template: "{{ state_attr('remote.living_room', 'current_activity') }}"
      friendly_name: Harmony

    den_media:
      value_template: "{{ state_attr('media_player.den_roku', 'source') }}"
      friendly_name: 'Den TV Source'

    bedroom_media:
      value_template: "{{ state_attr('media_player.bedroom_roku', 'source') }}"
      friendly_name: 'Bedroom TV Source'
    
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: unifigateway
  host: 192.168.2.62
  username: colemamd
  password: !secret unifi-pass
  monitored_conditions:
    - www
    - lan
    - wan
    - wlan
    - alerts
    - firmware

- platform: uptime
  name: HASS uptime
  unit_of_measurement: hours

- platform: version
  name: Current Version
  source: local

- platform: version
  name: Version Available
  source: docker
  image: default

- platform: zoneminder  
