# UPS sensor
- platform: apcupsd
  resources:
    - bcharge
    - timeleft
    - linev
    - loadpct
    - nominv
    - nompower
    - numxfers
    - lastxfer
    - status
    - tonbatt
    - cumonbatt
    - battv
    - nombattv

- platform: deluge
  host: 192.168.2.100
  username: !secret deluge_user
  password: !secret deluge_pass
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'

- platform: filesize
  file_paths:
    - /config/home-assistant_v2.db

- platform: glances
  name: pi_hole
  host: 192.168.2.254

- platform: mqtt
  name: "Washing Machine Power"
  state_topic: "tele/sonoff/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"

- platform: mqtt
  name: "Washing Machine Current"
  state_topic: "tele/sonoff/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Current"] }}'
  unit_of_measurement: "A"

- platform: template
  sensors:
    harmony_hub:
      value_template: "{{ state_attr('remote.living_room', 'current_activity') }}"
      friendly_name: Harmony

    den_media:
      value_template: "{{ state_attr('media_player.den_roku', 'source') }}"
      friendly_name: 'Den TV Source'

    bedroom_media:
      value_template: "{{ state_attr('media_player.bedroom_roku', 'source') }}"
      friendly_name: 'Bedroom TV Source'

- platform: netgear_enhanced
  host: 192.168.2.253
  username: !secret netgear_user
  password: !secret netgear_password
  resources:
    - firmware
    - check_app_fw
    - get_device_config_info
    - traffic_meter
    - traffic_meter_on
    - traffic_meter_options
    - get_lan_config_info
    - parental_control_on
    - mac_address
    - info
    - supported_features
    - speed_test_result
    - qos_enabled
    - bw_control
    - 2g_guest_wifi_on
    - 5g_guest_wifi_on
    - 2g_wpa_key
    - 5g_wpa_key
    - 2g_wifi_info
    - 5g_wifi_info
    - get_channel
    - 2g_guest_wifi_info
    - 5g_guest_wifi_info
    - get_smart_conn

- platform: uptime
  name: HASS uptime
  unit_of_measurement: hours

- platform: version
  name: Current Version
  source: local

- platform: version
  name: Version Available
  source: docker
  image: default

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: openweathermap
  api_key: !secret openweathermap-api_key
  monitored_conditions:
    - weather
  forecast: true
