# UPS sensor
- platform: apcupsd
  resources:
    - bcharge
    - timeleft
    - linev
    - loadpct
    - nominv
    - nompower
    - numxfers
    - lastxfer
    - status
    - tonbatt
    - cumonbatt
    - battv
    - nombattv

- platform: deluge
  host: 192.168.2.100
  username: !secret deluge_user
  password: !secret deluge_pass
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'

- platform: mqtt
  name: "Washing Machine Power"
  state_topic: "tele/sonoff/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"

- platform: mqtt
  name: "Washing Machine Current"
  state_topic: "tele/sonoff/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Current"] }}'
  unit_of_measurement: "A"

- platform: template
  sensors:
    harmony_hub:
      value_template: "{{ state_attr('remote.living_room', 'current_activity') }}"
      friendly_name: Harmony

    den_media:
      value_template: "{{ state_attr('media_player.den_roku', 'source') }}"
      friendly_name: 'Den TV Source'

    bedroom_media:
      value_template: "{{ state_attr('media_player.bedroom_roku', 'source') }}"
      friendly_name: 'Bedroom TV Source'

- platform: uptime
  name: HASS uptime
  unit_of_measurement: hours

- platform: version
  name: Current Version
  source: local

- platform: version
  name: Version Available
  source: docker
  image: raspberrypi3

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: openweathermap
  api_key: !secret openweathermap-api_key
  monitored_conditions:
    - weather
  forecast: true
