# SSL cert expiration check
- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/hass.colemanonline.net/cert.pem | awk '{print $NF}'"

# UPS sensor
- platform: apcupsd
  resources:
    - bcharge
    - linev
    - loadpct
    - nominv
    - nompower
    - numxfers
    - outputv
    - status
    - timeleft
    - tonbatt

# Weather Alerts
- platform: rest
  resource: https://api.weather.gov/alerts/active/count
  name: NWS Alert Count
  value_template: >
    {% if value_json.zones.GAZ166 is defined %}
      {{ value_json.zones.GAZ166 }}
    {% else %}
      0
    {% endif %}
  #json_attributes:
  #  - event
  #  - description
  #  - instructions
  #  - expires
  headers:
    User-Agent: Homeassistant
    Accept: application/ld+json
  scan_interval: 60

- platform: rest
  resource: https://api.weather.gov/alerts/active?zone=GAZ166
  name: NWS Alert Event
  value_template: >
    {% if value_json.features[0] is defined %}
      {{ value_json['features'][0]['properties'].event }}
    {% else %}
      None
    {% endif %}
  json_attributes:
    - features
  headers:
    User-Agent: Homeassistant
    Accept: application/geo+json
  scan_interval: 60
- platform: template
  sensors:
  #Waze travel time
    dest_address:
      value_template: >-
        {%- if is_state("input_select.destination", "Home") -%}
          416 McQueen Cir, Saint Marys, GA 31558, USA
        {%- elif is_state("input_select.destination", "Work") -%}
          1059 USS Mariano G Vallejo Ave, Saint Marys, GA 31558, USA
        {%- elif is_state("input_select.destination", "Nicholas") -%}
          309 Beautyberry Road, Summerville, SC 29486, USA
        {%- elif is_state("input_select.destination", "Johnathon") -%}
          8 Crossview Lane, Palm Coast, FL 32137, USA
        {%- else -%}
          Unknown
        {%- endif %}

    harmony_hub:
      value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
      friendly_name: Harmony

    den_media:
      value_template: '{{ states.media_player.den.attributes.source }}'
      friendly_name: 'Den TV Source'

- platform: waze_travel_time
  name: "Me to destination"
  origin: 416 McQueen Cir, Saint Marys, GA 31558, USA
  destination: sensor.dest_address
  region: 'US'
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: openweathermap
  api_key: 81e80c34304f0cacbd35743bbec78d16
  monitored_conditions:
    - weather
  forecast: true
