# UPS sensor
- platform: apcupsd
  resources:
    - bcharge
    - timeleft
    - linev
    - loadpct
    - nominv
    - nompower
    - numxfers
    - lastxfer
    - status
    - tonbatt
    - cumonbatt
    - battv
    - nombattv

- platform: glances
  version: 3
  name: "HASS"
  resources:
    - disk_use_percent
    - disk_free
    - memory_use_percent
    - memory_free
    - swap_use_percent
    - swap_free
    - processor_load
    - process_running
    - process_total
    - process_thread
    - cpu_use_percent
    - docker_active
    - docker_cpu_use
    - docker_memory_use

- platform: glances
  version: 3
  name: "torrent-pi"
  resources:
    - disk_use_percent
    - disk_free
    - memory_use_percent
    - memory_free
    - swap_use_percent
    - swap_free
    - processor_load
    - process_running
    - process_total
    - process_thread
    - cpu_use_percent

- platform: glances
  version: 3
  name: "pihole"
  resources:
    - disk_use_percent
    - disk_free
    - memory_use_percent
    - memory_free
    - swap_use_percent
    - swap_free
    - processor_load
    - process_running
    - process_total
    - process_thread
    - cpu_use_percent

- platform: mqtt
  name: "Washing Machine Power"
  state_topic: "tele/sonoff/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"

- platform: mqtt
  name: "Washing Machine Current"
  state_topic: "tele/sonoff/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Current"] }}'
  unit_of_measurement: "A"

- platform: template
  sensors:
    harmony_hub:
      value_template: '{{ states.remote.living_room.attributes.current_activity }}'
      friendly_name: Harmony

    den_media:
      value_template: '{{ states.media_player.den_roku.attributes.source }}'
      friendly_name: 'Den TV Source'

    bedroom_media:
      value_template: '{{ states.media_player.bedroom_roku.attributes.source }}'
      friendly_name: 'Bedroom TV Source'

- platform: uptime
  name: HASS uptime
  unit_of_measurement: hours

- platform: version
  name: Current Version
  source: local

- platform: version
  name: Version Available
  source: docker
  image: raspberrypi3

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'

- platform: openweathermap
  api_key: !secret openweathermap-api_key
  monitored_conditions:
    - weather
  forecast: true
